### ISSUE TITLE
Error running Python script wakeword.py

### ISSUE THREAD

**Issue by candrea21** [matrix-io/matrix-core-examples#1]
By trying to run ```python wakeword.py``` a get the error

```
Traceback (most recent call last):
  File "wakeword.py", line 12, in <module>
    from utils import driver_keep_alive, register_data_callback, register_error_callback
ImportError: cannot import name driver_keep_alive
```
Any ideas?

**Comment by Hermitter** [comment]
Hey @candrea21, thanks for the heads up! I've updated the [wakeword.py](https://github.com/matrix-io/matrix-core-examples/blob/master/python/wakeword.py) example. Let us know if this resolves your issue.

**Comment by Hermitter** [comment]
Since there hasn't been any activity in the past two weeks, I'll be marking this issue as closed.

**Comment by candrea21** [comment]
Thanks for the update. I realised that ``utils`` package is not from the python repository but from your ``matrix-io`` repository, i.e. https://raw.githubusercontent.com/matrix-io/matrix-creator-malos/master/src/python_test/utils.py
